### PR TITLE
fix: Fixed ui and added zero state for no category choosen

### PR DESCRIPTION
**Pull request by NoaRaz74**
Should fix: #295
1. Fixed ui problems like the footer being outside the page and the ability to scroll the whole page,
moved some buttons to be in better placement. (dev's support to footer and add site to the navbar instead of floating)
2. Improved how scrollbars looked and deleted irrelevant scrollbars
3. The part which solved #295, created zero state, some text when there is no category choosen

Developed with @eranpenso

### CODE REVIEW

**Review by 4tal — CHANGES_REQUESTED** [review]
Great! 
1. On the new page you've added on the mobile view footer. its missing the icons and the sentence.
2. We did a major change last night on #321. I prefer to finalize it before final review of your changes.

**Comment by eranpenso** [comment]
> Great!
> 
> 1. On the new page you've added on the mobile view footer. its missing the icons and the sentence.
> 2. We did a major change last night on [Details in popup #321](https://github.com/4tals/LinksForIsrael/pull/321). I prefer to finalize it before final review of your changes.


> Great!
> 
> 1. On the new page you've added on the mobile view footer. its missing the icons and the sentence.
> 2. We did a major change last night on [Details in popup #321](https://github.com/4tals/LinksForIsrael/pull/321). I prefer to finalize it before final review of your changes.

Didn’t notice the bug on the footer, maybe my device and my devtool sizes were not targeting the bug, i would love to see a screenshot to see what are you talking about

Thanks :)

**Comment by 4tal** [comment]
@eranpenso 
image

**Comment by 4tal** [comment]
#321 merged with many changes. Apologies for blocking. It will be great if you can take a look and submit improvements. @eranpenso

**Comment by eranpenso** [comment]
Good evening,  I fixed the bug with the footer and solved conflicts
@4tal requested changes are fixed and done

**Review by 4tal — APPROVED** [review]

**Pull request merged**
