### PR TITLE
Update Hamal Yozmot data

### PR DESCRIPTION
**Pull request by Yarondr**

### CODE REVIEW

**Comment by ohadschn** [comment]
@Yarondr the general assistance category is special, in that we display it alongside every other category.
This is only meant for very broad initiatives that do basically everything, like the facebook group [מתנדבי חרבות ברזל](https://www.facebook.com/groups/780925150471197/)
I don't think "Hamal Yozmot" meets this criteria

**Review by ohadschn — CHANGES_REQUESTED** [review]
See my comment in the discussion tab

**Comment by Yarondr** [comment]
@ohadschn thanks for your response. Our various initiatives provide hands-on assistance in diverse social as well as larger issues, from logistics, through immediate medical assistance, and even cyber security services for families from the south.
For your convenience, I am attaching the link to our website for your possible reevaluation of our Hamal: [yozmot.org.il](https://yozmot.org.il).

**Comment by ohadschn** [comment]
> @ohadschn thanks for your response. Our various initiatives provide hands-on assistance in diverse social as well as larger issues, from logistics, through immediate medical assistance, and even cyber security services for families from the south. For your convenience, I am attaching the link to our website for your possible reevaluation of our Hamal: [yozmot.org.il](https://yozmot.org.il).

I revisited the Yozmot site, and I believe there is a distinction to be made in terms of categorization.

The Yozmot site itself is a platform for creating initiatives. Yes, those initiatives could be in any field (cyber, logistics, security etc).  However, if I understand correctly, your Oprtaions room doesn't directly handle any general assistance request. Rather, as far as I understand it serves two functions:
1. Help create new initiatives or join existing ones you manage.
2. Index and possibly direct callers to one of your initiatives (if a relevant one exists).

So I'd say function (1) puts you in the `TechInitiatives/Main` category (similar to DevHelps).

Function (2) could in theory place you in the `Initiatives/Main` category (which should have been better named to something like `Initiative/Aggregators`), because in that capacity you serve as an aggregator. This is different than `GeneralAssistance`, which is reserved for operation rooms one can call with virtually any request and they'll take care of it organically (like https://www.hamal.org.il). 

However, I think `TechInitiatives/Main` is the more fitting category here - as excellent as your current 8 initiatives are, there are probably dozens if not hundreds others out there (the main reason why our site exists is to map them). Your main business is creating initiatives - not mapping them. And seeing as your expertise is technological, I think that's what makes the most sense.

**Pull request merged**
